### ISSUE TITLE
Decide if to merge this with the bootstrap lite project

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/bootstrap5_lite#1]
I've started this so we can collaborate without conflicting versions etc. Happy to merge this into the original if this is thought to be the best suggestion.
@stpaultim @bugfolder?

**Comment by bugfolder** [comment]
It would be nice to include it in Bootstrap Lite as a separate branch from the v3-based version.

Just looking at version numbering of current Bootstrap Lite...

[Drupal version](https://www.drupal.org/project/bootstrap_lite) is at 7.x-1.1. Hasn't been updated since 2016, so it's a reasonable assumption that the Drupal version isn't going to change.

[Backdrop version](https://backdropcms.org/project/bootstrap_lite) is currently at 1.x-1.3.6. That version number probably will change (we hope).

Even with a totally implemented v5 version with migration path from the v3-based D7 version, we'd still want to keep the v3 version around to support all the people migrating from D7 who have lots of CSS theming that assumes v3. So we'd want to support two releases going forward: a v3 release, and a v5 release.

BackdropCMS.org supports listing multiple releases on the project page if they differ in major version number.

So, what about this:

We keep the v3-based version to have major version 1.x-1.x.x, and then make the v5-based version 1.x-2.x.x.

Or we could make the major version match the underlying library, but we'd have to renumber the v3 version to 1.x-3.x.x, then the v5-based version could be 1.x-5.x.x (and that leaves room for someone to come along and do a v4-based version if they were so inclined).

What do y'all think?

**Comment by bugfolder** [comment]
We're in the process (I think) of bumping the version numbering of [Views Bootstrap](https://github.com/backdrop-contrib/views_bootstrap) to 1.x-3.5 ([see this PR](https://github.com/backdrop-contrib/views_bootstrap/pull/55)).

That suggests using the 1.x-3.x.x numbering for both modules for BSv3-based releases, and then 1.x-5.x.x numbering for BSv5-based releases (and perhaps there might be a BSv5 version of Views Bootstrap in the future?).

**Comment by klonos** [comment]
>Or we could make the major version match the underlying library, but we'd have to renumber the v3 version to 1.x-3.x.x, then the v5-based version could be 1.x-5.x.x (and that leaves room for someone to come along and do a v4-based version if they were so inclined).


Yes, I think that this makes the most sense.

Having said that, if Bootstrap-based (sub)themes are incompatible between major versions of Bootstrap, then perhaps it does make sense to keep these as separate projects. My point being that beginners to Drupal/Backdrop may think that a 1.x-5.x.x version is an "upgrade" for their existing 1.x-3.x.x (sub)theme, they update to it, and then their sites "break". Whereas if these are kept as separate projects, the 1.x-5.x.x version of bootstrap5_lite won't be shown to people as an available update for bootstrap_lite 1.x-3.x.x.

**Comment by bugfolder** [comment]
> beginners to Drupal/Backdrop may think that a 1.x-5.x.x version is an "upgrade" for their existing 1.x-3.x.x (sub)theme

No question that if multiple versions are supported in the same module, the README file needs to be pretty clear about which version to use and why.

**Comment by stpaultim** [comment]
In a previous discussion, we were leaning towards keeping Bootstrap Lite focused on Bootstrap 3 and creating a new project for newer versions of Bootstrap. 
https://github.com/backdrop-contrib/bootstrap_lite/issues/17

This makes sense to me for some of the reasons mentioned above. However, I'm open to discussion on this.

**Comment by klonos** [comment]
Wondering if something like this would work in the `bootstrap_lite.info` file:

- for 1.x-3.x:
  ```
  dependencies[] = bootstrap_lite (< 1.x-4.0)
  ```
- for 1.x-4.x:
  ```
  dependencies[] = bootstrap_lite (>= 1.x-4.0, < 1.x-5.0)
  ```
- for 1.x-5.x:
  ```
  dependencies[] = bootstrap_lite (>= 1.x-5.0, < 1.x-6.0)
  ```

See https://docs.backdropcms.org/creating-modules#info-files

That would prevent people from shooting their own feet (would force different major versions of the project to be incompatible with each other, and disallow updating from one to the other automatically via the admin UI).

**Comment by bugfolder** [comment]
@stpaultim, I think I was one of the ones advocating for keeping BSL focused on 3! But I've changed my mind based on further input. At the time, I'd been thinking in terms of a single version that had a switch to choose between BS versions, and I thought that would be unwieldy. But the concept now being discussed, of having multiple versions of the same module seems like a better fit.

**Comment by stpaultim** [comment]
If @bugfolder, @docwilmot, and @klonos all like the idea of merging these two projects using the versioning system described above, I'm good with that. 

@docwilmot - having put the time into this version of Bootstrap that you did - I would be happy to cede my role as maintainer of Bootstrap Lite to you and @bugfolder (or it could be the three of us, I'd take a backup role). 

I largely stepped in as maintainer of Bootstrap Lite, because there was none. Since then @bugfolder has really taken on a large role and I've not done much.

**Comment by bugfolder** [comment]
@klonos, I can imagine use cases where someone actually would want to update to a newer version of Bootstrap, so we shouldn't rule that out fully. (And is it possible to make a module depend on itself?)

**Comment by bugfolder** [comment]
@docwilmot, if you're OK with the merge, then I'm thinking these would be the next steps:

1. We make you a co-maintainer of Bootstrap Lite.
2. We open a 1.x-5.x branch in Bootstrap Lite.
3. You move your code into that branch, and away we go.

I did think of one more factor that dissuades having multiple branches, though. On the Backdrop module page, the version with the highest major version number is "Recommended release", with others being "Other releases". ([See, for example, here.](https://backdropcms.org/project/ubercart)) And in the module page search results, only the recommended version is shown, so some people might go immediately to download that.

In this case, though, we don't really want to make 1.x-5.x the "recommended" version for all the people migrating from D7.

Would that be problematic?

**Comment by yorkshire-pudding** [comment]
Interesting discussion.  I don't know if any other themes currently have more than one release.  I had a quick look but it wasn't obvious.  The key for novice users might be what will install when they click add to installation queue and click Install (that's how I currently do it as not yet taken the plunge with command line on backdrop).

**Comment by docwilmot** [comment]
I dont know really. Normally, different branches/releases imply new approaches with an upgrade path. This is a new frontend library. You wont find anyone really switching versions as such right? It would be a different theme altogether. I'm happy to keep it separate.

I only just discovered Bootstrap lite and really like it, so I'm thinking instead of starting of my usage with 3.x I might as well get off with the latest and greatest, so I'm pushing to get 5.x up to scratch. So far I think I've covered enough to get a release. Please review if you can find some time.

**Comment by bugfolder** [comment]
Yes, after considering all of those factors (and having bounced back and forth), it does seem simplest to just keep them as separate projects. It's easy enough (and perfectly clear) to say in the relevant README files "if you need to use Bootstrap X, try this module," and then no worries about versions within the module.

I'll take it for a spin in the near future.

**Comment by stpaultim** [comment]
I don't feel strongly one was or another. However, in my view a user is much less likely to upgrade from one minor version of a theme than they would a module. Example: 1.x-2.x to 1.x-3.x. 

With a theme, the reason for creating a new minor version probably to make a bunch of changes or restructuring that is likely to break a sites theme. The idea is to make a new and improved version of the theme for future users of the theme, not to provide new features for sites that are already using the theme. At least, that's how I see it.

I know that with the Zen theme in Drupal, each new minor version introduced new build tools or restructured files in ways that meant I would never upgrade the theme on an existing site between minor versions. However, I would generally used the latest version when I start a new site. 

So, I think that the way Zen handled versions in Drupal 7 is not that different from what we might be proposing here.

**Comment by irinaz** [comment]
I am looking for bootstrap 5 theme for Backdrop, what are issues that are blocking this project from release?

**Comment by docwilmot** [comment]
None of the remaining issues are major, and I expected that we could release this as soon as we had sufficient feedback. Its been three months now and also I think projects get much more exposure once released. So I think its time, in other words.

The last important question is about this one, which I propose to leave separate. Unless there is some strong disagreement, I'll release this week.

**Comment by irinaz** [comment]
I agree that it is better to have this theme separate, both for new projects and those that are using bootstrap_lite now.  Looking forward to release and adding this theme through standard Backdrop UI :). 
Thanks for making this theme!

**Comment by izmeez** [comment]
As a new entrant it is certainly easier to understand with separate projects, realizing subthemes aren't going to magically upgrade.

**Comment by irinaz** [comment]
@izmeez , thank for your comment. @docwilmot , can we close this issue as resolved?  I do not have permissions to Close with Comment :)
