### ISSUE TITLE
Grids in Webform

### ISSUE THREAD

**Issue by tkcent** [backdrop-contrib/bootstrap5_lite#10]
I don't see an easy way to add Bootstrap grids to webforms within fieldsets.  While you can add column classes to the individual field wrapper elements, there still needs to be parent divs with .container and .row classes.

https://getbootstrap.com/docs/5.1/layout/grid/

There is already a line for modifying the fieldset wrapper, so I am wondering if it makes sense to just add an extra div.

In template.php:

Line 268:   $output .= \'\<div class=\"fieldset-wrapper card-body **container**\"\>**\<div class=\"row\"\>**\';
Line 276:   $output .= \'**\</div\>**\</div\>\';

More than happy to create a pull request if that sounds reasonable.

**Comment by docwilmot** [comment]
Excuse the delay.  This makes sense, a PR would be welcome.

**Comment by tkcent** [comment]
Pull request added #15

**Comment by docwilmot** [comment]
Reconsidering this. I've Googled and not found this to be standard. Cards are already "containers" in Bootstrap it seems, and I dont feel that columns in a card (or a webform in a fieldset) is that much of a common case.

**Comment by tkcent** [comment]
I would say multiple columns in webforms is pretty common for most cases with more than a few fields, especially things like registration forms which I do quite often.  Without creating hook_form_alter functions or webform template files I'm not really seeing a way to create webforms with multiple horizontal columns using bootstrap grid classes. 

Here is an example of what is required for Drupal:

https://getlevelten.com/blog/kristin-brinner/how-use-drupal-bootstrap-webforms

I like how Backdrop focuses on the content creator/site builder experience so it seems like it would be a good idea to make it a straightforward process through the webform UI.

Is there a container element where the .container and .row bootstrap classes can be added so that textfield, email and other elements can be styled with bootstrap .col-xxx classes?  The fieldset element doesn't allow you to modify the div wrapper inside that holds all the fields, just the fieldset element itself.

**Comment by docwilmot** [comment]
OK, I see that you mean Webform child components within a Webform parent fieldset component, which makes sense. But still again, we'd be adding an additional styled `div` in everyone's cards, just to satisfy this unusual use case. I don't think we should do that. I think this will have to be left to the user to theme on their own.

**Comment by tkcent** [comment]
Closing
