### ISSUE TITLE
Bug in vertical tabs classes

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/bootstrap5_lite#19]
I am setting display for a content type that has many fields using vertical tabs group and vertical tabs.  Bootstrap5 adds  the following classes to element fieldset
` class="group-structure field-group-tab form-wrapper card card-default vertical-tabs-pane"`
As a result display for class card from _card.css 
```
.card {
    position: relative;
    display: flex;
```
is conflicting with display for class "vertical-tabs-pane".

Attached are screenshots of out of the box page and correct display when I manually remove class "card".

I am not sure what is best way to address this issue.
<img width="572" alt="Screen Shot 2022-01-24 at 7 30 54 PM" src="https://user-images.githubusercontent.com/2497005/150906072-0ac1246f-41e7-464a-a9ee-312c4656fb76.png">

<img width="789" alt="Screen Shot 2022-01-24 at 7 32 05 PM" src="https://user-images.githubusercontent.com/2497005/150906068-b5318f55-43e1-495a-9eff-5047ccc1b21b.png">

**Comment by docwilmot** [comment]
@irinaz I looked at this and the latest code *should* already exclude vertical tabs with
```
bootstrap5_lite_fieldset($variables) {
  if (isset($variables['element']['#group_fieldset']) && !empty($variables['element']['#group_fieldset']) || !empty($variables['element']['#groups']['vertical_tabs'])) {
    return theme_fieldset($variables);
```
On my local vertical tabs dont get the card class. Are you using the latest?

**Comment by irinaz** [comment]
@docwilmot , I tested on a new site with most recent version of the theme and I see the same result  here https://dev-cmqcc-2.pantheonsite.io/.   Looking through the code it seems that it is still going through lines 284/85.

**Comment by docwilmot** [comment]
Strange. How are those tabs generated? Can you post the code?

**Comment by irinaz** [comment]
They are generated via UI, I added two fields and three groups to page content type and configured them to display as vertical tabs. I am attaching screenshot of display configuration and full export of site configuration.  Let me know if it is hepful.

<img width="1187" alt="Screen Shot 2022-03-26 at 7 36 01 PM" src="https://user-images.githubusercontent.com/2497005/160264274-52e2864f-9426-4696-b364-3a462d5b08e0.png">
[cmqcc-2-config.tar.gz](https://github.com/backdrop-contrib/bootstrap5_lite/files/8356715/cmqcc-2-config.tar.gz)

**Comment by docwilmot** [comment]
So youre using Field Group module then?

**Comment by irinaz** [comment]
Yes, I am using it to configure vertical tabs.  I do not do that programmatically.

**Comment by docwilmot** [comment]
OK, I wouldnt want to stop all fieldsets having the card classes, since sites may already be using this style, so we'd need to detect if this fieldset is in a Field Group vertical tab. But I cannot figure out a satisfactory way to do this. Added a check for Field Group class. 😞 

Please see if that helps.

**Comment by irinaz** [comment]
I am testing new code, but I also have configurations with horizontal tabs.  attached is zip with more complex html, it has class " horizontal-tabs-pane"  for fieldset.  I will do more testing and add update here, but maybe we can figure out approach that will be more generic, as there are more options in display settings.   
Thanks you for looking into this!
[fieldset-html.html.zip](https://github.com/backdrop-contrib/bootstrap5_lite/files/8359477/fieldset-html.html.zip)

**Comment by docwilmot** [comment]
I just realised Field Group has an API, so new approach should remove card for all vtabs.

**Comment by docwilmot** [comment]
@irinaz did you manage to test this new approach yet? Can I push new release and close this?

**Comment by irinaz** [comment]
Not yet, sorry, I will try this week. My apologies.

**Comment by yorkshire-pudding** [comment]
> 

Reminder @irinaz

**Comment by irinaz** [comment]
@yorkshire-pudding , thank you so much for the ping!  @docwilmot , almost a year later I confirm that I tested and new approach fixes this problem.  Closing this issue. 
Thank you!!

**Comment by yorkshire-pudding** [comment]
Shouldn't be closed yet, as I think @docwilmot will need to merge in the PR (#23)

**Comment by bugfolder** [comment]
If I'm understanding the discussion above, the changes from last year fix the issue, and we no longer need to remove the `card` and `card-default` classes from all fieldsets, since they're now selectively left out of vtabs. (Also PR #23 comments out code, rather than removing it.) So I think we can re-close the issue and PR #23.

**Comment by irinaz** [comment]
Sounds good, we will be working with this theme in the next few months, I can reopen this ticket if there is still a problem
