### ISSUE TITLE
Figure out how to add classes to <a> links

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/bootstrap5_lite#2]
I can see how classes can be added to `<li class="myclass">` tags, with difficulty, but cant figure how to add classes to the actual `<a class="myclass">` tags within the `li` tags. 

This would help with a change from V3 in a few places since there is now a `.nav-link` class on these links that the CSS is targeting in places, such as `.nav-tabs .nav-link` for theming local task tabs.

**Comment by docwilmot** [comment]
This may have been fixed by https://github.com/backdrop-contrib/bootstrap5_lite/commit/ee105d80ca6f00bc2e48887e48086527d8132b38. Leaving open as I'm not entirely sure this is the best way to achieve it.

**Comment by irinaz** [comment]
@docwilmot , this fix has been committed to the theme, right?

**Comment by docwilmot** [comment]
Yes, it was, but I wasnt sure about the approach. Seems to be without concern so far though, so will close.
