### ISSUE TITLE
Additional classes for grid display

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/bootstrap5_lite#20]
Hi, 
I want to add two classes to make grid display easier,   in which file I should add them - overrides.css or another?

@media (min-width: 732px) {
.grid-three {
    display: grid;
    grid-template-columns: 30% 30% 30%;
    column-gap: 5%;
}
.grid-four {
    display: grid;
    grid-template-columns: 22% 22% 22% 22%;
    column-gap: 3%;
}
}

**Comment by docwilmot** [comment]
@irinaz I dont know the implications of combining bootstrap's grid system with CSS grid. At the very least, I dont want to include this in a Bootstrap theme. Are you asking for this to be added to the core Bootstrap CSS or were you asking how best to add it to your subtheme?

**Comment by irinaz** [comment]
Current theme has three files in css folder https://github.com/backdrop-contrib/bootstrap5_lite/tree/1.x-1.x/css.  I would like to add grid-three and grid-four classes in one of those as we are using them on each site.  My hope is to provide modern light theme with maximum features and flexibility out of the box for all users of Backdrop.  
I know how to add css to our subtheme, thanks you for asking.

**Comment by bugfolder** [comment]
The Bootstrap library has [its own way of doing grids](https://getbootstrap.com/docs/5.1/layout/grid/); IMO adding a second way of creating grids seems like it would lead to some user confusion (however elegant the CSS `display: grid` is on its own merits).

At the moment, I'm not aware of any module (or subtheme) that builds upon the Bootstrap 5 grid the way that the (Bootstrap 3-based) [Views Bootstrap module](https://backdropcms.org/project/views_bootstrap) builds upon the Bootstrap 3 grids (and so is a natural companion to the [Boostrap Lite theme](https://backdropcms.org/project/bootstrap_lite)). But if someone builds a "Views Bootstrap 5" module, it would presumably make use of the Bootstrap 5 grid classes.

All of which is to say, providing a theme or module that creates a nice set of CSS `display: grid` classes seems like a good and useful thing, but this doesn't seem like the right place for it.

**Comment by irinaz** [comment]
Thanks, I will test Views Bootstrap module.  I started using CSS `display: grid`  because  Bootstrap library requires setup of container/row/col and often it is very hard to configure without rewriting theme.  But if this theme is not the right place to add this  CSS `display: grid`  then we will keep it in subtheme
