### ISSUE TITLE
Bootswatch theme settings page does not show current bootswatch theme selected

### ISSUE THREAD

**Issue by rayjamesdev** [backdrop-contrib/bootstrap5_lite#27]
When going to theme settings -> Bootswatch Theme tab, it does not show which Bootswatch Theme is currently selected.

Steps to reproduce:
- Install Bootstrap 5 Lite theme, optionally create subtheme
- Go to theme settings -> Bootswatch Theme tab
- Select any Bootswatch theme, hit save
- Screen will refresh but the Bootswatch theme that was selected will not show as selected.

Additionally, after selecting a Bootswatch theme, there is no option to go back to whatever the theme was after fresh install.
Thanks for your time.

**Comment by izmeez** [comment]
I also find this confusing. User can click to select a Bootswatch theme but not unselect it with ctrl-click (or whatever a mobile equivalent might be). I wondered if this has to do with the first option being "Default Pure Bootstrap CSS" and needing to click that. If that is the case it would be useful to have that set by default and to have the currently selected theme visible marked when returning to the page.

Also a reset default option might help.

And adding a tool tip on hover over the radio box "click to select" may be a further help.

**Comment by izmeez** [comment]
Turns out I was mistaken, selecting "Default" does not return to "none" so the OP is correct, there is no way to revert to the local "fresh" install theme.

**Comment by izmeez** [comment]
The only solution is to disable the theme and enable it again to reset all settings.

**Comment by bugfolder** [comment]
I think the problem is that the theme setting for `bootstrap5_lite_bootswatch` is uninitialized, i.e., the .info file should contain
```
settings[bootstrap5_lite_bootswatch] = ""
```

That's why the "default" button appears unselected initially. It should be selected initially.

PR to follow.
