### ISSUE TITLE
Bootstrap 5 Lite project page documentation url link typo

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/bootstrap5_lite#29]
On the https://backdropcms.org/project/bootstrap5_lite page under the heading "Documentation" Additional documentation is located in the wiki. The link url is wrong, the ending "/Documentation" needs to be removed. The right sidebar link is correct. Thanks.

**Comment by bugfolder** [comment]
The quoted text is no longer on that page. Closing.
