### ISSUE TITLE
How to upgrade CDN to newer version

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/bootstrap5_lite#30]
Just new to Backdrop and the Bootstrap5 Lite theme. Currently Bootstrap5 Lite is configured to go up to version 5.0.1 and the current new version of Bootstrap is 5.3.1 and also the theme supports Font Awesome up to 4.4.0 and the version 6.2.1 of Font Awesome is the new one.  Can the Bootstrap5 Lite be modified to use the newer CDN versions? Can a subtheme be configured to use the newer CDN versions?

**Comment by bugfolder** [comment]
The supported CDN versions of Bootstrap 5 are hard-coded in the theme settings, but it is a simple change to add CDN support for 5.3.1 (without changing the bundled version, preserving backwards compatibility). PR to follow.

**Comment by bugfolder** [comment]
Waiting on the maintainer (ping @docwilmot ) to merge https://github.com/backdrop-contrib/bootstrap5_lite/pull/17 (from https://github.com/backdrop-contrib/bootstrap5_lite/issues/16). Since new versions of Bootstrap 5 and FontAwesome have come out, I can add the latest versions to that PR.

**Comment by bugfolder** [comment]
Note that in that PR, FontAwesome is unbundled (and is unneeded for the basic theme), but you can use the separate [FontAwesome module](https://backdropcms.org/project/fontawesome) to use other FA icons. You can also use the [Bootstrap Icons](https://backdropcms.org/project/bootstrap_icons) module.

**Comment by izmeez** [comment]
Yes, I've been looking at using those and they can also we used with other themes.
