### ISSUE TITLE
How to make 3-promoted-cards view responsive on front page

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/bootstrap5_lite#31]
Currently the 3 promoted cards view on the front page shows the 3 cards becoming narrower with narrow screens. How can they made to be responsive so that they are displayed vertically on a narrow screen?

**Comment by Egmund** [comment]
I have the same problem.
My solution was to change layout to one with an area with three equal side-by-side blocks like Geary Hero and then insert the cards into these boxes.

**Comment by izmeez** [comment]
Thanks for bringing this back.
~It looks like the problem described in the OP is gone, like it was fixed,~ the cards on the Backdrop default Basis theme front page are responsive. Easy to create a demo at https://backdropcms.org/demo to confirm.
The suggestion to use a layout with three equal columns, like Geary Hero, could also be used in a mini-layout, although a flexible-layout is an alternative choice.
We have seen similar problems on some themes and applied css fixes.

**Comment by izmeez** [comment]
Ah, sorry ... it is still not fixed on default install of Bootstrap5_Lite. Correct.

**Comment by Egmund** [comment]
Yes, it is a Bootstrap5_lite problem -not a general other themes works just fine.

**Comment by robertgarrigos** [comment]
I added a PR which fixes this by applying some of the cards.css styles that basis applies. However, I wonder if I would be better to apply bootstrap grid classes by overriding views.view.grid.tpl.php file...

**Comment by docwilmot** [comment]
I believe this is a core issue actually: we don't have any CSS to handle window resizing with View grid code. Meanwhile could we just override all grids instead of being specific to the cards? See PR comment.
