### ISSUE TITLE
Dropbuttons need styling as links

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/bootstrap5_lite#36]
Core changes in 1.25.2 fixed a width problem with dropbuttons, but they're not styled as links:

![image](https://github.com/backdrop-contrib/bootstrap5_lite/assets/29214084/ce345754-68e7-4ee6-a674-c7aa89570d81)

The same issue is addressed in Bootstrap Lite, https://github.com/backdrop-contrib/bootstrap_lite/issues/59.

A test View is

[views.view.dropbutton_test.json.txt](https://github.com/backdrop-contrib/bootstrap5_lite/files/13467565/views.view.dropbutton_test.json.txt)

**Comment by bugfolder** [comment]
Link colors are Bootswatch-specific, so added CSS would need to also be Bootswatch-specific.

**Comment by robertgarrigos** [comment]
Added a PR which fixes this. It also applies Bootswatch-specific colors. Would you test it? Thanks.

**Comment by docwilmot** [comment]
Looks good.
