### ISSUE TITLE
Navbar seems to always have light style

### ISSUE THREAD

**Issue by sdubois** [backdrop-contrib/bootstrap5_lite#37]
I have a question about the navbar styling with the bootswatch selection.

It seems like no matter which bootswatch theme I select, the navbar style is always a light color (light grey). This does not match the thumbnail preview color. For example, Yeti shows a blue navbar in in the thumbnail selector

<img width="351" alt="image" src="https://github.com/backdrop-contrib/bootstrap5_lite/assets/479460/3201b1ad-f433-4f61-a8ab-8ede989bd20b">

But when I save, the result is grey

<img width="992" alt="image" src="https://github.com/backdrop-contrib/bootstrap5_lite/assets/479460/ae374c62-1b0a-4126-b743-110abe597850">

Selecting " Inverse navbar style" does not appear to change anything. 

It appears that this styling is caused by the navbar-light and bg-light classes on the body element. I feel like the expected behavior is that the default classes should be navbar-primary and bg-primary.

**Comment by robertgarrigos** [comment]
Added a PR to fix this. Would you test it? Thanks.

**Comment by docwilmot** [comment]
RTBC
