### ISSUE TITLE
Progress Bar's Auto-refresh Broken

### ISSUE THREAD

**Issue by rbargerhuff** [backdrop-contrib/bootstrap5_lite#38]
This concerns `template.php`, Line 1039

Line must be changed to :

`$output .= '<div class="progress">';` 

Not doing so breaks the autofresh for progress bars which is crucial for _Views Bulk Operations_ to function properly.

This is because in `core/misc/batch.js`, line 9, which defines `$progress`, by using a jQuery selector that selects the element based on the id of the container.

Leaving out `.=` prevents the parent container `progress` from being defined.

**Comment by rbargerhuff** [comment]
Why has this not received any attention? Is this project dead? https://github.com/backdrop-contrib/bootstrap5_lite/commit/185eda4461c0021f25e2ea76730552e89cdc975c

**Comment by bugfolder** [comment]
Not dead, just overlooked. Checking now.

**Comment by bugfolder** [comment]
Function needs a docblock, too.

**Comment by bugfolder** [comment]
@rbargerhuff, there's a PR now: can you test and verify that it fixes the issue for you? (It should, it's just got your change plus the docblock added, but it would be nice to get confirmation.)

**Comment by rbargerhuff** [comment]
PR tested as it should. Fix was identical to what we had already implemented on our own local version. Thank you for taking care of this issue.
