### ISSUE TITLE
Adds its own opinionated css to placeholder class, such as in messages

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/bootstrap5_lite#41]
It's supposed to say the view name but it has a `placeholder` class which Bootstrap 5 heavily styles with changing the background colour, opacity and the cursor:

![Screenshot from 2024-07-05 11-14-53](https://github.com/backdrop-contrib/bootstrap5_lite/assets/1071483/3349762a-c525-4ad6-a898-d8384472214d)

I assume placeholder means something special in Bootstrap and Backdrop has a different meaning.

**Comment by robertgarrigos** [comment]
I believe this doesn't apply anymore. I cannot see where or when it has been fixed, but I remember having this error also. However, I cannot reproduce it now with the latest release.

**Comment by robertgarrigos** [comment]
Ah, just come across this again. I will file a PR
