### ISSUE TITLE
Help to maintain this project

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/bootstrap5_lite#43]
I would like to help to maintain this project. I will create the pr to add my name to the README.md

**Comment by bugfolder** [comment]
Fine by me!

**Comment by robertgarrigos** [comment]
Should I wait for Andy's opinion before I merge my name in the README?

**Comment by bugfolder** [comment]
Yeah, he originally created the module (though I've been helping out). But I see in Zulip that he's OK with it, so merge away.
